from typing import Optional, List

from .github_object import GithubObject
from .license import License
from .object import Object
from .repo_permissions import RepoPermissions


class Repository(Object):

    def __init__(
            self,
            *,
            id: Optional['int'] = None,
            node_id: Optional['str'] = None,
            name: Optional['str'] = None,
            full_name: Optional['str'] = None,
            private: Optional['bool'] = None,
            owner: Optional['GithubObject'] = None,
            html_url: Optional['str'] = None,
            description: Optional['str'] = None,
            fork: Optional['bool'] = None,
            url: Optional['str'] = None,
            forks_url: Optional['str'] = None,
            keys_url: Optional['str'] = None,
            collaborators_url: Optional['str'] = None,
            teams_url: Optional['str'] = None,
            hooks_url: Optional['str'] = None,
            issue_events_url: Optional['str'] = None,
            events_url: Optional['str'] = None,
            assignees_url: Optional['str'] = None,
            branches_url: Optional['str'] = None,
            tags_url: Optional['str'] = None,
            blobs_urls: Optional['str'] = None,
            git_tags_url: Optional['str'] = None,
            git_refs_url: Optional['str'] = None,
            trees_url: Optional['str'] = None,
            statuses_url: Optional['str'] = None,
            languages_url: Optional['str'] = None,
            stargazers_url: Optional['str'] = None,
            contributors_url: Optional['str'] = None,
            subscribers_url: Optional['str'] = None,
            subscription_url: Optional['str'] = None,
            commits_url: Optional['str'] = None,
            git_commits_url: Optional['str'] = None,
            comments_url: Optional['str'] = None,
            issue_comments_url: Optional['str'] = None,
            contents_url: Optional['str'] = None,
            compare_url: Optional['str'] = None,
            merges_url: Optional['str'] = None,
            archive_url: Optional['str'] = None,
            downloads_url: Optional['str'] = None,
            issues_url: Optional['str'] = None,
            pulls_url: Optional['str'] = None,
            milestones_url: Optional['str'] = None,
            notifications_url: Optional['str'] = None,
            labels_url: Optional['str'] = None,
            releases_url: Optional['str'] = None,
            deployments_url: Optional['str'] = None,
            created_at: Optional['str'] = None,
            updated_at: Optional['str'] = None,
            pushed_at: Optional['str'] = None,
            git_url: Optional['str'] = None,
            ssh_url: Optional['str'] = None,
            clone_url: Optional['str'] = None,
            svn_url: Optional['str'] = None,
            homepage: Optional['str'] = None,
            size: Optional['int'] = None,
            stargazers_count: Optional['int'] = None,
            watchers_count: Optional['int'] = None,
            language: Optional['str'] = None,
            has_issues: Optional['bool'] = None,
            has_projects: Optional['bool'] = None,
            has_downloads: Optional['bool'] = None,
            has_wiki: Optional['bool'] = None,
            has_pages: Optional['bool'] = None,
            forks_count: Optional['int'] = None,
            mirror_url: Optional['str'] = None,
            archived: Optional['bool'] = None,
            disabled: Optional['bool'] = None,
            open_issues_count: Optional['int'] = None,
            license: Optional['License'] = None,
            allow_forking: Optional['bool'] = None,
            is_template: Optional['bool'] = None,
            topics: List['str'] = None,
            visibility: Optional['str'] = None,
            forks: Optional['int'] = None,
            open_issues: Optional['int'] = None,
            watchers: Optional['int'] = None,
            default_branch: Optional['str'] = None,
            permissions: Optional['RepoPermissions'] = None,
    ):
        self.id = id
        self.node_id = node_id
        self.name = name
        self.full_name = full_name
        self.private = private
        self.owner = owner
        self.html_url = html_url
        self.description = description
        self.fork = fork
        self.url = url
        self.forks_url = forks_url
        self.keys_url = keys_url
        self.collaborators_url = collaborators_url
        self.teams_url = teams_url
        self.hooks_url = hooks_url
        self.issue_events_url = issue_events_url
        self.events_url = events_url
        self.assignees_url = assignees_url
        self.branches_url = branches_url
        self.tags_url = tags_url
        self.blobs_urls = blobs_urls
        self.git_tags_url = git_tags_url
        self.git_refs_url = git_refs_url
        self.trees_url = trees_url
        self.statuses_url = statuses_url
        self.languages_url = languages_url
        self.stargazers_url = stargazers_url
        self.contributors_url = contributors_url
        self.subscribers_url = subscribers_url
        self.subscription_url = subscription_url
        self.commits_url = commits_url
        self.git_commits_url = git_commits_url
        self.comments_url = comments_url
        self.issue_comments_url = issue_comments_url
        self.contents_url = contents_url
        self.compare_url = compare_url
        self.merges_url = merges_url
        self.archive_url = archive_url
        self.downloads_url = downloads_url
        self.issues_url = issues_url
        self.pulls_url = pulls_url
        self.milestones_url = milestones_url
        self.notifications_url = notifications_url
        self.labels_url = labels_url
        self.releases_url = releases_url
        self.deployments_url = deployments_url
        self.created_at = created_at
        self.updated_at = updated_at
        self.pushed_at = pushed_at
        self.git_url = git_url
        self.ssh_url = ssh_url
        self.clone_url = clone_url
        self.svn_url = svn_url
        self.homepage = homepage
        self.size = size
        self.stargazers_count = stargazers_count
        self.watchers_count = watchers_count
        self.language = language
        self.has_issues = has_issues
        self.has_projects = has_projects
        self.has_downloads = has_downloads
        self.has_wiki = has_wiki
        self.has_pages = has_pages
        self.forks_count = forks_count
        self.mirror_url = mirror_url
        self.archived = archived
        self.disabled = disabled
        self.open_issues_count = open_issues_count
        self.license = license
        self.allow_forking = allow_forking
        self.is_template = is_template
        self.topics = topics
        self.visibility = visibility
        self.forks = forks
        self.open_issues = open_issues
        self.watchers = watchers
        self.default_branch = default_branch
        self.permissions = permissions

    @staticmethod
    def _parse(repo: dict) -> Optional['Repository']:
        if repo is None or not len(repo):
            return None

        return Repository(
            id=repo.get('id', None),
            node_id=repo.get('node_id', None),
            name=repo.get('name', None),
            full_name=repo.get('full_name', None),
            private=repo.get('private', None),
            owner=GithubObject._parse(repo.get('owner', None)),
            html_url=repo.get('html_url', None),
            description=repo.get('description', None),
            fork=repo.get('fork', None),
            url=repo.get('url', None),
            forks_url=repo.get('forks_url', None),
            keys_url=repo.get('keys_url', None),
            collaborators_url=repo.get('collaborators_url', None),
            teams_url=repo.get('teams_url', None),
            hooks_url=repo.get('hooks_url', None),
            issue_events_url=repo.get('issue_events_url', None),
            events_url=repo.get('events_url', None),
            assignees_url=repo.get('assignees_url', None),
            branches_url=repo.get('branches_url', None),
            tags_url=repo.get('tags_url', None),
            blobs_urls=repo.get('blobs_urls', None),
            git_tags_url=repo.get('git_tags_url', None),
            git_refs_url=repo.get('git_refs_url', None),
            trees_url=repo.get('trees_url', None),
            statuses_url=repo.get('statuses_url', None),
            languages_url=repo.get('languages_url', None),
            stargazers_url=repo.get('stargazers_url', None),
            contributors_url=repo.get('contributors_url', None),
            subscribers_url=repo.get('subscribers_url', None),
            subscription_url=repo.get('subscription_url', None),
            commits_url=repo.get('commits_url', None),
            git_commits_url=repo.get('git_commits_url', None),
            comments_url=repo.get('comments_url', None),
            issue_comments_url=repo.get('issue_comments_url', None),
            contents_url=repo.get('contents_url', None),
            compare_url=repo.get('compare_url', None),
            merges_url=repo.get('merges_url', None),
            archive_url=repo.get('archive_url', None),
            downloads_url=repo.get('downloads_url', None),
            issues_url=repo.get('issues_url', None),
            pulls_url=repo.get('pulls_url', None),
            milestones_url=repo.get('milestones_url', None),
            notifications_url=repo.get('notifications_url', None),
            labels_url=repo.get('labels_url', None),
            releases_url=repo.get('releases_url', None),
            deployments_url=repo.get('deployments_url', None),
            created_at=repo.get('created_at', None),
            updated_at=repo.get('updated_at', None),
            pushed_at=repo.get('pushed_at', None),
            git_url=repo.get('git_url', None),
            ssh_url=repo.get('ssh_url', None),
            clone_url=repo.get('clone_url', None),
            svn_url=repo.get('svn_url', None),
            homepage=repo.get('homepage', None),
            size=repo.get('size', None),
            stargazers_count=repo.get('stargazers_count', None),
            watchers_count=repo.get('watchers_count', None),
            language=repo.get('language', None),
            has_issues=repo.get('has_issues', None),
            has_projects=repo.get('has_projects', None),
            has_downloads=repo.get('has_downloads', None),
            has_wiki=repo.get('has_wiki', None),
            has_pages=repo.get('has_pages', None),
            forks_count=repo.get('forks_count', None),
            mirror_url=repo.get('mirror_url', None),
            archived=repo.get('archived', None),
            disabled=repo.get('disabled', None),
            open_issues_count=repo.get('open_issues_count', None),
            license=License._parse(repo.get('license', None)),
            allow_forking=repo.get('allow_forking', None),
            is_template=repo.get('is_template', None),
            topics=repo.get('topics', list(), ),
            visibility=repo.get('visibility', None),
            forks=repo.get('forks', None),
            open_issues=repo.get('open_issues', None),
            watchers=repo.get('watchers', None),
            default_branch=repo.get('default_branch', None),
            permissions=RepoPermissions._parse(repo.get('permissions', None)),
        )
